global:
  domain: localhost
  publicPort: 80

images:
  pullPolicy: IfNotPresent
  wordpress: conduit/wordpress:6.7.2-wc9.6.2
  mariadb: mariadb:11.4.5
  wooMcp: conduit/woo-mcp:latest

storage:
  className: local-path
  mariadbSize: 5Gi
  wpContentSize: 2Gi

secrets:
  existingStoreSecret: store-secrets

ingress:
  className: traefik
  tls:
    enabled: false
    clusterIssuer: letsencrypt-prod

networkPolicy:
  enabled: true
