apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "woocommerce-store.fullname" . }}-config
  namespace: store-default
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
data:
  WP_SITEURL: "http://shop.{{ .Values.global.domain }}"
  WP_HOME: "http://shop.{{ .Values.global.domain }}"
