apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "woocommerce-store.fullname" . }}-mariadb
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  serviceName: {{ include "woocommerce-store.fullname" . }}-mariadb
  replicas: 1
  selector:
    matchLabels:
      {{- include "woocommerce-store.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mariadb
  template:
    metadata:
      labels:
        {{- include "woocommerce-store.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mariadb
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mariadb
          image: "{{ .Values.images.mariadb | default "mariadb:11.4.5" }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingStoreSecret }}
                  key: MARIADB_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingStoreSecret }}
                  key: MARIADB_PASSWORD
          startupProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            failureThreshold: 30
            periodSeconds: 2
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["mariadb-admin", "ping", "-u", "root", "-p$(MYSQL_ROOT_PASSWORD)"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "woocommerce-store.labels" . | nindent 10 }}
        annotations:
          helm.sh/resource-policy: keep
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storage.className }}
        resources:
          requests:
            storage: {{ .Values.storage.mariadbSize }}
