apiVersion: v1
kind: Service
metadata:
  name: {{ include "woocommerce-store.fullname" . }}-mariadb
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    {{- include "woocommerce-store.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
